### ISSUE TITLE
maxout in ssd_head.py

### ISSUE THREAD

**Issue by Guocode** [610265158/DSFD-tensorflow#12]
```
                    if cfg.MODEL.maxout and i==0:
                        cla_out = self.max_out_cla(feature_halo,ratios_per_pixel,cla_num=cfg.DATA.num_class,scope='maxout%d'%i)
                    else:
                        cla_out = slim.conv2d(feature_halo, ratios_per_pixel*cfg.DATA.num_class, [3, 3], stride=1, activation_fn=None,normalizer_fn=None, scope='out_cla%d'%i)

```

why the  fms[1]  do the maxout.

Another problem which I think is a small bug lies in line104 in dataietr.py, which do the operation of remove the small face, boxes_clean is not used to replace the origin boxes.

**Comment by 610265158** [comment]
Hi,
The first feature map is large, the anchor is small and dense, and it  leads to more false positive, maxout can effectively decrease it.

Yes you are right, it is a bug. Thank you for pointing  it out.

**Comment by Guocode** [comment]
Thanks for reply !
