### ISSUE TITLE
Is the model quantized?

### ISSUE THREAD

**Issue by akhil451** [610265158/DSFD-tensorflow#13]
I wanted to know the model provided here is quantized? When I was running it for a video, the model hogged the GPU memory even though it was set to be using only 50 percent by the author and was also not able to perform inference on a video frame as the process got killed because of lack of gpu-memory.

When I tried to quantize the model. It showed it was a frozen graph and not a saved .pb file. Can you provide that file also.

**Comment by akhil451** [comment]
System info:
Intel i5 
GTX 1060 6GB

**Comment by 610265158** [comment]
hi,
Yes, the pb file is freezed. However,i think there is no need to quantize the model, for the reason that the model is so large. 
We should develop a light model if necessary.

And you can do such things from the ckpt file.

Good luck

**Comment by 610265158** [comment]
hi,
Yes, the pb file is freezed. However,i think there is no need to quantize the model, for the reason that the model is so large.

**Comment by akhil451** [comment]
Can you provide the ckpt file for this model so I can test the change in performance.

**Comment by 610265158** [comment]
Yes, i will upload it later.

**Comment by akhil451** [comment]
Thank you.

**Comment by 610265158** [comment]
Hi，
Now, you can download the ckpt from the googledrive link in the readme file.
