### ISSUE TITLE
About epoch

### ISSUE THREAD

**Issue by HsiaoCH** [610265158/DSFD-tensorflow#2]
config.TRAIN.epoch = 2000
Need to be so big?
one day I can run epoch 28, so I run epoch 2000 I need 71 days?

**Comment by 610265158** [comment]
> config.TRAIN.epoch = 2000
> Need to be so big?
> one day I can run epoch 28, so I run epoch 2000 I need 71 days?

no, there is no need for that, the epoch is not that useful. just make the training keep going

**Comment by HsiaoCH** [comment]
Ok, I understand.
