### ISSUE TITLE
Tf-2.0 branch training no batch after first epoch

### ISSUE THREAD

**Issue by foreverhoulu** [610265158/DSFD-tensorflow#20]
Hi ：
Great work！
I tried to train a new  dsfd model with branch tf 2.0，and I am not able to make it work 
After debugging  for some time，I found it would not generate any batch data after first epoch？
So，on which branch does the pretrained model trained？
and how to make adjustments to make it work？
thx～

**Comment by 610265158** [comment]
Sorry for reply late.
I thought that it the tensorpack version problem, please try with tensorpack 0.9.9, or lower

**Comment by foreverhoulu** [comment]
I have tried and It worked ,thx!
