### ISSUE TITLE
About download a pretrained model(detector.pb)

### ISSUE THREAD

**Issue by HsiaoCH** [610265158/DSFD-tensorflow#3]
Not available:
https://pan.baidu.com/s/1SRMoJIcqHRoVydl2XIZ3lA

**Comment by 610265158** [comment]
> Not available:
> https://pan.baidu.com/s/1SRMoJIcqHRoVydl2XIZ3lA

maybe u need the key  'm3bg'

but it is really slow download the model from baiduyun, i suggested the train your own model, 
if u want a train fast u could set input size as 320, it still can work
the model now is not perform so well on widerface hard case, and i am still woking on that,

**Comment by HsiaoCH** [comment]
Thank you for your reply
