### ISSUE TITLE
KeyError while training for tensorpack

### ISSUE THREAD

**Issue by KD1994** [610265158/DSFD-tensorflow#5]
Hi,

I'm trying to run this on Google colab, while i'm facing this issue for the tensorpack.
Do you have any idea how i can resolve this?

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-33-6ad3a7012249> in <module>()
> ----> 1 from lib.core.base_trainer.net_work import trainner
>       2 import setproctitle
>       3 
>       4 setproctitle.setproctitle("detect")
>       5 
> 
> 4 frames
> /content/drive/My Drive/DSFD-tensorflow-master/lib/core/base_trainer/net_work.py in <module>()
>      10 from functools import partial
>      11 
> ---> 12 from lib.dataset.dataietr import DsfdDataIter
>      13 from lib.core.model.net.ssd import SSD
>      14 from train_config import config as cfg
> 
> /content/drive/My Drive/DSFD-tensorflow-master/lib/dataset/dataietr.py in <module>()
>      10 
>      11 from lib.helper.logger import logger
> ---> 12 from tensorpack.dataflow import DataFromList
>      13 from tensorpack.dataflow import BatchData, MultiThreadMapData, MultiProcessPrefetchData
>      14 
> 
> /usr/local/lib/python3.6/dist-packages/tensorpack/__init__.py in <module>()
>       6 
>       7 from tensorpack.utils import *
> ----> 8 from tensorpack.dataflow import *
>       9 
>      10 # dataflow can be used alone without installing tensorflow
> 
> /usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/__init__.py in <module>()
>      46     if not module_name.startswith('_') and \
>      47             module_name not in __SKIP:
> ---> 48         _global_import(module_name)
>      49 
>      50 
> 
> /usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/__init__.py in _global_import(name)
>      30     lst = p.__all__ if '__all__' in dir(p) else dir(p)
>      31     if lst:
> ---> 32         del globals()[name]
>      33         for k in lst:
>      34             if not k.startswith('__'):
> 
> KeyError: 'base'

Any suggestion would be great.
Thank you

**Comment by 610265158** [comment]
> Hi,
> 
> I'm trying to run this on Google colab, while i'm facing this issue for the tensorpack.
> Do you have any idea how i can resolve this?
> 
> > KeyError                                  Traceback (most recent call last)
> >  in ()
> > ----> 1 from lib.core.base_trainer.net_work import trainner
> > 2 import setproctitle
> > 3
> > 4 setproctitle.setproctitle("detect")
> > 5
> > 4 frames
> > /content/drive/My Drive/DSFD-tensorflow-master/lib/core/base_trainer/net_work.py in ()
> > 10 from functools import partial
> > 11
> > ---> 12 from lib.dataset.dataietr import DsfdDataIter
> > 13 from lib.core.model.net.ssd import SSD
> > 14 from train_config import config as cfg
> > /content/drive/My Drive/DSFD-tensorflow-master/lib/dataset/dataietr.py in ()
> > 10
> > 11 from lib.helper.logger import logger
> > ---> 12 from tensorpack.dataflow import DataFromList
> > 13 from tensorpack.dataflow import BatchData, MultiThreadMapData, MultiProcessPrefetchData
> > 14
> > /usr/local/lib/python3.6/dist-packages/tensorpack/**init**.py in ()
> > 6
> > 7 from tensorpack.utils import *
> > ----> 8 from tensorpack.dataflow import *
> > 9
> > 10 # dataflow can be used alone without installing tensorflow
> > /usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/**init**.py in ()
> > 46     if not module_name.startswith('_') and 
> > 47             module_name not in __SKIP:
> > ---> 48         _global_import(module_name)
> > 49
> > 50
> > /usr/local/lib/python3.6/dist-packages/tensorpack/dataflow/**init**.py in _global_import(name)
> > 30     lst = p.**all** if '**all**' in dir(p) else dir(p)
> > 31     if lst:
> > ---> 32         del globals()[name]
> > 33         for k in lst:
> > 34             if not k.startswith('__'):
> > KeyError: 'base'
> 
> Any suggestion would be great.
> Thank you

hi,
Firstly, i sugget that using anaconda, :)
The tensorpack version i use is 0.9.6.
And seems like, it is a python package import problem. U could print the global(), see if there is base.

thaks

**Comment by KD1994** [comment]
Thanks for the response.
I don't have GPU with me now, so was hoping to train the model on Google colab:sweat_smile:

Anyways thanks for the suggestion I'll take a look into this.
