### ISSUE TITLE
Port to tensorflow.js

### ISSUE THREAD

**Issue by MariasStory** [610265158/DSFD-tensorflow#7]
Hi, thanks for the interesting solution.
Will you be porting/converting trained models to tensorflow.js?

Maybe, you can help to integrate it in the face-api project:
https://github.com/justadudewhohacks/face-api.js

**Comment by 610265158** [comment]
> Hi, thanks for the interesting solution.
> Will you be porting/converting trained models to tensorflow.js?
> 
> Maybe, you can help to integrate it in the face-api project:
> https://github.com/justadudewhohacks/face-api.js

hi,  
I am not familiar with js. 
But i would like to give it a try  when i have time.  : )

thanks.

**Comment by MariasStory** [comment]
You can check this one:
https://github.com/tensorflow/tfjs-converter

**Comment by 610265158** [comment]
> You can check this one:
> https://github.com/tensorflow/tfjs-converter

hi，the model there is pretty heavy,   i think convert to js model is not suitable in this situation , 
maybe a light model is needed :(

thanks
