### ISSUE TITLE
Download pertained model (detector.pb)

### ISSUE THREAD

**Issue by KD1994** [610265158/DSFD-tensorflow#8]
Hi,

Thanks for providing the TF version of DSFD.
Just want to ask you if possible, would you be able to upload pre-trained model to Google drive. Baidu is not accessible from everywhere.

I'd really appreciate that.

**Comment by 610265158** [comment]
> Hi,
> 
> Thanks for providing the TF version of DSFD.
> Just want to ask you if possible, would you be able to upload pre-trained model to Google drive. Baidu is not accessible from everywhere.
> 
> I'd really appreciate that.

hi,  
Thanks for paying attention to the project
And there is a problem with Google drive for me, and i will upload it when i fix it. : )

thanks

**Comment by 610265158** [comment]
> Hi,
> 
> Thanks for providing the TF version of DSFD.
> Just want to ask you if possible, would you be able to upload pre-trained model to Google drive. Baidu is not accessible from everywhere.
> 
> I'd really appreciate that.

hi, 
now you can download the pb model from google drive, 
https://drive.google.com/drive/folders/1zCeXPdRPG6-4W8fqEl4uRD5ojHbDRH-o

thanks

**Comment by KD1994** [comment]
Thank you very much. really appreciated.
