### ISSUE TITLE
测试速度

### ISSUE THREAD

**Issue by HandsLing** [610265158/DSFD-tensorflow#9]
请问您这个代码在测试图片的时候能达到多少fps呢？

**Comment by 610265158** [comment]
> 请问您这个代码在测试图片的时候能达到多少fps呢？

hi,
it depends on the input size,
for example, input size with 416x416 needs about 15ms  on a 2080ti gpu (backbone with vgg).
thanks

**Comment by HandsLing** [comment]
> 
> 
> > 请问您这个代码在测试图片的时候能达到多少fps呢？
> 
> hi,
> it depends on the input size,
> for example, input size with 416x416 needs about 15ms on a 2080ti gpu (backbone with vgg).
> thanks
Thanks for your reply.
I resized the input image to (416*416),and i need about 153ms on a P40 gpu, does it normal?
And can this code run in a higher version of tensorflow?

**Comment by HandsLing** [comment]
@610265158 
Thanks for your reply.
I resized the input image to (416*416),and i need about 153ms on a P40 gpu, does it normal?
And can this code run in a higher version of tensorflow?

**Comment by HandsLing** [comment]
@610265158 
我还有一个问题。这个代码可以从ckpt文件中加载模型数据吗？我改代码让他从ckpt文件中加载模型，但是报错了，还是我的数据输入格式不对呢？

**Comment by 610265158** [comment]
> @610265158
> 我还有一个问题。这个代码可以从ckpt文件中加载模型数据吗？我改代码让他从ckpt文件中加载模型，但是报错了，还是我的数据输入格式不对呢？

1. For input size 416, i think 153ms is not correct.
2. Hgher version of tensorflow should be ok.   
    ps, tensorflow now update in a high speed， i am always confuse about the api now :( 
3. ckpt is fine, u should init the detector as 
     `face_detector = FaceDetector([***.ckpt.meta,**.ckpt.data]) `  

contact me if u have problem!

**Comment by HandsLing** [comment]
@610265158 
我们能加个好友吗？
QQ或是微信？
或者邮箱联系也行
我的QQ：529617728
微信：18271393959
邮箱：lck1994@foxmail.com
有很多问题想请教，谢谢您

**Comment by 610265158** [comment]
problem solved

**Comment by dhuQChen** [comment]
Why does one image(300 * 500) cost 1.5s for me?  Thanks for reply!
